FROM phusion/baseimage:latest
MANTAINER That guy

RUN mkdir /var/lib/mysql && chmod 777 /var/lib/mysql
#COPY /var/lib/mysql from host or RUN run.sh with mysql installation
VOLUME /var/lib/mysql
CMD /bin/bash
